### ISSUE TITLE
Option to run with only a single membership

### ISSUE THREAD

**Issue by BerglundDaniel** [makerspace/makeradmin#388]
Many makerspaces only have one typ of membership instead of one for the association and one for the premise. I think the main work here is too have another registration page as an option and have one membership that adds both memership days and labaccess days.

**Comment by amrsoll** [comment]
Is it realistic to have db entries that describe all of these?
- Subscription name
- cost
- recurrence
- description (including emojis would be nice)
- discounts
- dependency (fx. lab access requires basic membership?)

Then there would be a possibility to have multiple memberships.

See #331

I might have mentioned that I find a config file to be just as good a place to have info as a database. It is easier to migrate/recreate the website if the subscriptions are fully described in a config file. 

Example subscriptions.yml

```yml
membership:
  price: 200
  recurrence: yearly
  description:
    - "line 1"
    - "line 2"
makerspace_access:
  price: 300
  recurrence: monthly
  depends: membership
  description:
    - "line A"
    - "line B"
```
